# Generated by Django 3.0.5 on 2020-04-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('creator_username', models.CharField(blank=True, max_length=127, null=True)),
                ('reading_list_name', models.CharField(blank=True, max_length=30, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('creator_username', models.CharField(blank=True, max_length=127, null=True)),
            ],
        ),
    ]
