INSERT INTO states(id,name,abbreviation,population) VALUES (1,'Alabama','AL',4849377);
INSERT INTO states(id,name,abbreviation,population) VALUES (2,'Alaska','AK',736732);
INSERT INTO states(id,name,abbreviation,population) VALUES (3,'Arizona','AZ',6731484);
INSERT INTO states(id,name,abbreviation,population) VALUES (4,'Arkansas','AR',2966369);
INSERT INTO states(id,name,abbreviation,population) VALUES (5,'California','CA',38802500);
INSERT INTO states(id,name,abbreviation,population) VALUES (6,'Colorado','CO',5355866);
INSERT INTO states(id,name,abbreviation,population) VALUES (7,'Connecticut','CT',3596677);
INSERT INTO states(id,name,abbreviation,population) VALUES (8,'Delaware','DE',935614);
INSERT INTO states(id,name,abbreviation,population) VALUES (9,'District of Columbia','DC',658893);
INSERT INTO states(id,name,abbreviation,population) VALUES (10,'Florida','FL',19893297);
INSERT INTO states(id,name,abbreviation,population) VALUES (11,'Georgia','GA',10097343);
INSERT INTO states(id,name,abbreviation,population) VALUES (12,'Hawaii','HI',1419561);
INSERT INTO states(id,name,abbreviation,population) VALUES (13,'Idaho','ID',1634464);
INSERT INTO states(id,name,abbreviation,population) VALUES (14,'Illinois','IL',12880580);
INSERT INTO states(id,name,abbreviation,population) VALUES (15,'Indiana','IN',6596855);
INSERT INTO states(id,name,abbreviation,population) VALUES (16,'Iowa','IA',3107126);
INSERT INTO states(id,name,abbreviation,population) VALUES (17,'Kansas','KS',2904021);
INSERT INTO states(id,name,abbreviation,population) VALUES (18,'Kentucky','KY',4413457);
INSERT INTO states(id,name,abbreviation,population) VALUES (19,'Louisiana','LA',4649676);
INSERT INTO states(id,name,abbreviation,population) VALUES (20,'Maine','ME',1330089);
INSERT INTO states(id,name,abbreviation,population) VALUES (21,'Maryland','MD',5976407);
INSERT INTO states(id,name,abbreviation,population) VALUES (22,'Massachusetts','MA',6745408);
INSERT INTO states(id,name,abbreviation,population) VALUES (23,'Michigan','MI',9909877);
INSERT INTO states(id,name,abbreviation,population) VALUES (24,'Minnesota','MN',5457173);
INSERT INTO states(id,name,abbreviation,population) VALUES (25,'Mississippi','MS',2994079);
INSERT INTO states(id,name,abbreviation,population) VALUES (26,'Missouri','MO',6063589);
INSERT INTO states(id,name,abbreviation,population) VALUES (27,'Montana','MT',1023579);
INSERT INTO states(id,name,abbreviation,population) VALUES (28,'Nebraska','NE',1881503);
INSERT INTO states(id,name,abbreviation,population) VALUES (29,'Nevada','NV',2839098);
INSERT INTO states(id,name,abbreviation,population) VALUES (30,'New Hampshire','NH',1326813);
INSERT INTO states(id,name,abbreviation,population) VALUES (31,'New Jersey','NJ',8938175);
INSERT INTO states(id,name,abbreviation,population) VALUES (32,'New Mexico','NM',2085572);
INSERT INTO states(id,name,abbreviation,population) VALUES (33,'New York','NY',19746227);
INSERT INTO states(id,name,abbreviation,population) VALUES (34,'North Carolina','NC',9943964);
INSERT INTO states(id,name,abbreviation,population) VALUES (35,'North Dakota','ND',739482);
INSERT INTO states(id,name,abbreviation,population) VALUES (36,'Ohio','OH',11594163);
INSERT INTO states(id,name,abbreviation,population) VALUES (37,'Oklahoma','OK',3878051);
INSERT INTO states(id,name,abbreviation,population) VALUES (38,'Oregon','OR',3970239);
INSERT INTO states(id,name,abbreviation,population) VALUES (39,'Pennsylvania','PA',12787209);
INSERT INTO states(id,name,abbreviation,population) VALUES (40,'Puerto Rico','PR',3548397);
INSERT INTO states(id,name,abbreviation,population) VALUES (41,'Rhode Island','RI',1055173);
INSERT INTO states(id,name,abbreviation,population) VALUES (42,'South Carolina','SC',4832482);
INSERT INTO states(id,name,abbreviation,population) VALUES (43,'South Dakota','SD',853175);
INSERT INTO states(id,name,abbreviation,population) VALUES (44,'Tennessee','TN',6549352);
INSERT INTO states(id,name,abbreviation,population) VALUES (45,'Texas','TX',26956958);
INSERT INTO states(id,name,abbreviation,population) VALUES (46,'Utah','UT',2942902);
INSERT INTO states(id,name,abbreviation,population) VALUES (47,'Vermont','VT',626562);
INSERT INTO states(id,name,abbreviation,population) VALUES (48,'Virginia','VA',8326289);
INSERT INTO states(id,name,abbreviation,population) VALUES (49,'Washington','WA',7061530);
INSERT INTO states(id,name,abbreviation,population) VALUES (50,'West Virginia','WV',1850326);
INSERT INTO states(id,name,abbreviation,population) VALUES (51,'Wisconsin','WI',5757564);
INSERT INTO states(id,name,abbreviation,population) VALUES (52,'Wyoming','WY',584153);

