# Generated by Django 4.2.5 on 2023-09-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book", name="cover_url", field=models.URLField(blank=True),
        ),
    ]
