# Generated by Django 4.2.5 on 2023-09-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microblog", "0002_auto_20180620_2013"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="tweet_images/"),
        ),
    ]
