# Generated by Django 2.0.6 on 2018-10-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shiba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_src', models.CharField(max_length=127)),
                ('name', models.CharField(max_length=127)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
