#!/bin/bash

# This is a helper Bash script to make it easier to see how adding constraints
# affects the SQL code that is generated by Django. Run it after making changes
# to `apps/core/models.py` to see the resulting SQL of those changes.

# Remove migration
rm ./apps/core/migrations/*.py

# Remake that migration
python manage.py makemigrations core

# Print some decorative text
echo '------------------------------------------'
echo '-- SQL                                  --'
echo '------------------------------------------'

# Finally, show the SQL generated by this migration
python manage.py sqlmigrate core 0001

