# Generated by Django 2.0.6 on 2018-06-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('street_address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('visit_date', models.DateField()),
            ],
        ),
    ]
