# Generated by Django 2.0.7 on 2019-07-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('reason_for_visit', models.CharField(max_length=100)),
                ('street_address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('visit_date', models.DateField()),
            ],
        ),
    ]
