# Generated by Django 2.1.2 on 2018-10-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
